version = 0.1

[default]
[default.global]
[default.global.parameters]
region = "ap-northeast-1"
stack_name = "MigrationToolStack"
s3_bucket = "siruko-cloudformation-templetes"

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_NAMED_IAM"