AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  ################################
  # Lambda and IAM
  ################################
  # define_src_data function
  F1LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../functions/define_src_data/
      Handler: app.handler
      Runtime: python3.9
      # Layers:
      #   - !Ref MyLayer
      Description: ''
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      Role: !GetAtt IAMRoleF1LambdaFunction.Arn
      FileSystemConfigs: []
      FunctionName: define_src_data
      PackageType: Zip
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/define_src_data
      EphemeralStorage:
        Size: 512
      Architectures:
        - x86_64

  # role for define_src_data function
  IAMRoleF1LambdaFunction:
    UpdateReplacePolicy: Retain
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      Path: /service-role/
      ManagedPolicyArns:
        - !Ref IAMManagedPolicyF1LambdaFunction
      MaxSessionDuration: 3600
      RoleName: IAMRoleF1LambdaFunction
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
  IAMManagedPolicyF1LambdaFunction:
    UpdateReplacePolicy: Retain
    Type: AWS::IAM::ManagedPolicy
    DeletionPolicy: Delete
    Properties:
      ManagedPolicyName: IAMManagedPolicyF1LambdaFunction
      Path: /service-role/
      Description: ''
      Groups: []
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
            Action: logs:CreateLogGroup
            Effect: Allow
          - Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/F1LambdaFunction:*
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
      Roles: []
      Users: []
